# -*- coding: utf-8 -*-
"""Cars Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lxc8HfE-MK1p704y5UQ_EvE15pecQupJ
"""

import pandas as pd

car=pd.read_csv("file.csv")

car.head()

car.shape

"""1) For Data Cleaning
# **Find all the null values and then fill it with the mean of that column**
"""

car.isnull().sum()

car['Cylinders'].fillna(car['Cylinders'].mean(), inplace=True)

# Calculate the mean for each numeric column
numeric_means = car.select_dtypes(include='number').mean()

# Fill NaN values in numeric columns with their respective mean
car.fillna(numeric_means, inplace=True)
# Calculate the mode for each non-numeric column
non_numeric_modes = car.select_dtypes(exclude='number').mode().iloc[0]

# Fill NaN values in non-numeric columns with their respective mode
car.fillna(non_numeric_modes, inplace=True)

# Now fill NaN values in numeric columns with their respective mean
numeric_means = car.select_dtypes(include='number').mean()
car.fillna(numeric_means, inplace=True)

car.isnull().sum()

"""2) Based on Value Counts
# **Check what are different types of Make and what is the count of each Make in dataset**
"""

car.head(2)

"""3) Filtering
# **Show all the records where Origin is Asia or Europe**


"""

car.head(2)

car['Make'].value_counts()

car[car['Origin'].isin(['Asia','Europe'])]

"""4) Remove unwanted records
# **Remove all the records (rows) where Weight is above 4000**
"""

car[~(car['Weight'] > 4000)]

"""5) Applying functio on a column
# **Increase all the values of "MPG_City" column by 3**
"""

car['MPG_City']= car['MPG_City'].apply(lambda x:x+3)

car